
project_id = "eglsybvrlegoqpvpqmda"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[functions]
[functions.create-checkout]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.subscription-portal]
verify_jwt = true
